const AUTHENTICATE_ROUTE = {
    LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
  };
  const APP_ROUTE = {
    MAIN_TAB: '@APP_ROUTE/MAIN_TAB',
  };
  const HOME_ROUTE = {
    ROOT: '@HOME_ROUTE/ROOT',
    HOME_SCREEN: '@HOME_ROUTE/HOME_SCREEN',
  };
  const PROFILE_ROUTE = {
    ROOT: '@PROFILE_ROUTE/ROOT',
    PROFILE_SCREEN: '@PROFILE_ROUTE/PROFILE/PROFILE_SCREEN',
  }
  const TAB_NAVIGATION_ROOT = {
    HOME_ROUTE,PROFILE_ROUTE
  };
  
  export {APP_ROUTE, TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE};